version: '2'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    links:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - DB_HOST=db
      - LOG_LEVEL=info

  db:
    image: rethinkdb
