version: '2'
services:
  client:
    build:
      context: .
      dockerfile: misc/Dockerfile.client
    ports:
      - "80:80"
    links:
      - server

  server:
    build:
      context: .
      dockerfile: misc/Dockerfile.server
    environment:
      - DB_HOST=db
      - LOG_LEVEL=info
    links:
      - db

  db:
    image: rethinkdb
